[package]
name = "modus"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
time = "0.3.36"
yahoo_finance_api = "2.1.0"
serde = { version = "1.0.200", features = ["derive"] }
chrono = "0.4.38"
rstat = "0.6.0"
serde_json = "1.0.116"